#set language to c because we are using conda to install everything
language: c
sudo: false
#set environment variables for versions of different packages
#set up the build matrix for multiple versions of python
env:
  global:
    - PYTHON_VERSION=2.7
    - NUMPY_VERSION='stable'
    - ASTROPY_VERSION='stable'
    - MAIN_CMD='python setup.py'
    - SETUP_CMD='install'
    - CONDA_DEPENDENCIES='scipy matplotlib ipython ipyparallel pyqt'
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.4
    - PYTHON_VERSION=3.5
#install the ci helpers
install:
  - git clone https://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_${TRAVIS_OS_NAME}.sh
#run the setup commands
script:
  - $MAIN_CMD $SETUP_CMD
