#set language to c because we are using conda to install everything
language: c
sudo: false
#set environment variables for versions of different packages
#set up the build matrix for multiple versions of python
env:
  global:
    - XUVTOP=$HOME"/chianti_dbase"
    - PYTHON_VERSION=2.7
    - NUMPY_VERSION='stable'
    - ASTROPY_VERSION='stable'
    - MAIN_CMD='python setup.py'
    - CONDA_DEPENDENCIES='scipy matplotlib ipython ipyparallel pyqt sphinx sphinx_rtd_theme pytest'
    - PYQT_VERSION='4.11.4'
  matrix:
    - PYTHON_VERSION=2.7 SETUP_CMD='install'
    - PYTHON_VERSION=3.4 SETUP_CMD='install'
    - PYTHON_VERSION=3.5 SETUP_CMD='install'
    - PYTHON_VERSION=2.7 SETUP_CMD='test'
    - PYTHON_VERSION=3.4 SETUP_CMD='test'
    - PYTHON_VERSION=3.5 SETUP_CMD='test'
    - PYTHON_VERSION=2.7 SETUP_CMD='build_sphinx'
    - PYTHON_VERSION=3.4 SETUP_CMD='build_sphinx'
    - PYTHON_VERSION=3.5 SETUP_CMD='build_sphinx'
#install the ci helpers
install:
  - git clone https://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_${TRAVIS_OS_NAME}.sh
#install the chianti database and place rc file
before_script:
  - mkdir -p $HOME/.chianti
  - cp chiantirc $HOME/.chianti
  - mkdir -p $XUVTOP
  - curl -L http://www.chiantidatabase.org/download/CHIANTI_8.0.2_data.tar.gz | tar xz -C $XUVTOP
#run the setup commands
script:
  - $MAIN_CMD $SETUP_CMD
