name: chiantipy
dependencies:
- backports_abc=0.4=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.9=py27_0
- freetype=2.5.5=0
- futures=3.0.5=py27_0
- ipykernel=4.3.1=py27_0
- ipyparallel=5.0.1=py27_0
- ipython=4.1.2=py27_2
- ipython_genutils=0.1.0=py27_0
- jupyter_client=4.2.2=py27_0
- jupyter_core=4.1.0=py27_0
- libpng=1.6.17=0
- matplotlib=1.5.1=np110py27_0
- mkl=11.3.1=0
- numpy=1.10.4=py27_0
- openssl=1.0.2g=0
- path.py=8.1.2=py27_1
- pexpect=4.0.1=py27_0
- pickleshare=0.5=py27_0
- pip=8.1.1=py27_1
- ptyprocess=0.5=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.5.1=py27_0
- pytz=2016.3=py27_0
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np110py27_0
- setuptools=20.6.7=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.2.1=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - alabaster==0.7.7
  - babel==2.2.0
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - certifi==2016.2.28
  - docutils==0.12
  - functools32==3.2.3.post2
  - gnureadline==6.3.3
  - imagesize==0.7.0
  - ipython-genutils==0.1.0
  - ipywidgets==4.1.1
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - markupsafe==0.23
  - mistune==0.7.2
  - nbconvert==4.1.0
  - nbformat==4.0.1
  - notebook==4.1.0
  - pygments==2.1.3
  - qtconsole==4.2.1
  - snowballstemmer==1.2.1
  - sphinx==1.4
  - sphinx-rtd-theme==0.1.9
  - terminado==0.6
